### ISSUE TITLE
Additional support for sublime-syntax grammar

### ISSUE THREAD

**Issue by gandm** [atom/first-mate#50]
Sublime text 3 has implemented a new grammar format that seems much better than the traditional textmate grammar. Is there any chance this can be implemented? 

It is described here https://www.sublimetext.com/docs/3/syntax.html

**Comment by Alhadis** [comment]
Seems to be a duplicate of #36.

**Comment by 50Wliu** [comment]
Thanks @Alhadis.

**Comment by gandm** [comment]
No it's not!

**Comment by Alhadis** [comment]
How? It seems to be syntactic sugar around the standard TextMate-grammar parsing.

**Comment by gandm** [comment]
No it's has a concept of state.

**Comment by Alhadis** [comment]
What do you mean, a concept of state?

**Comment by gandm** [comment]
For example you can match a single char, say a + sign and then follow this by pushing a number of contexts onto the stack. E.g. variable name, numeric number,... only one will pop the stack. This is hard in normal grammar as the only code that spans multiple lines is begin/end and you have to know what ends it before you start.

**Comment by gandm** [comment]
Having said that, I am not too bothered if the issue is closed.

**Comment by Alhadis** [comment]
It's possible through nested patterns, although ugly. So... theoretically, that's still syntactic sugar over what's already possible now.

**Comment by 50Wliu** [comment]
Thanks for explaining further @gandm - perhaps I should actually scroll down the link next time.  There is also variable support, which I don't think CSON has, so I'm going to re-open this.

**Comment by gandm** [comment]
All I can say is this would have made my life easier when I wrote [language-babel](https://atom.io/packages/language-babel)

**Comment by borela** [comment]
I wouldn't consider "just a syntax sugar" when it makes writing syntaxes a way easier than the traditional tmLanguage. Also you can have different control paths with `push` vs `set` and include external files which is perfect when dealing with lists of words like so: https://github.com/borela/naomi/blob/master/syntaxes/fjsx15/reactjs.sublime-syntax

**Comment by gandm** [comment]
tree-sitter soon available so closing.

**Comment by borela** [comment]
@gandm Can the sublime-syntax be converted to tree sitter?

**Comment by Arcanemagus** [comment]
For reference, @borela's question is answered in https://github.com/tree-sitter/tree-sitter/issues/139 😉.

**Comment by borela** [comment]
@Arcanemagus So far arguments in favor of tree sitter I heard only apply to limitations in the tmLanguage, you can assign the correct meaning to tokens using sublime syntax.

**Comment by gandm** [comment]
I think tree-sitter is vastly superior. Fast, accurate with additional intelligence. You cannot create a true language parser using sublime-syntax nor textmate. Certainly not JavaScript.

**Comment by Arcanemagus** [comment]
@borela There is a _major_ difference between a true parser such as what `tree-sitter` provides, and the attempts to hack together a similar result as is done in TextMate grammars... or Sublime Text's new format. I'd recommend reading up on parsers of context free grammars and if you still have questions feel free to follow up over in https://github.com/tree-sitter/tree-sitter/issues/139.

**Comment by borela** [comment]
@Arcanemagus that's what I was not getting, to me looked like tree sitter was just generating a tree which could be done by analyzing the scopes generated by the sublime syntax.

It didn't occur to me that tree sitter was also parsing.

**Comment by Alhadis** [comment]
> Certainly not JavaScript.

... lol, what the hell.

**Comment by borela** [comment]
@gandm You can assign the correct scopes using sublime syntax and even distinguish weather /abc/ is a regex literal or something divided by abc depending on whats before it, I did exactly that on Naomi, other packages [JSCustom](https://github.com/Thom1729/Sublime-JS-Custom/) does the same, the only limitation is the per line regex, but that's sublime's limitation.

But as I talked to Max, he did convinced me to use Tree Sitter for more complex languages (C++, MQL5, etc...) because I often have to deal with badly formatted code that spans across multiple lines.
