### ISSUE TITLE
Update oniguruma dependency to v6.1.0 to avoid stack trace on node >= v6.0.0

### ISSUE THREAD

**Issue by gamell** [atom/first-mate#72]
`(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated`

Is solved if oniguruma is updated to v6.1.0

**Comment by kentor** [comment]
any eta on this?

**Comment by zeke** [comment]
I'm seeing this too on Node 6.2. Full stack trace here: https://gist.github.com/zeke/a2142469200e0a1ecc9b4fff9c730a70

**Comment by gamell** [comment]
@zeke any plans to update oniguruma yet?

**Comment by zeke** [comment]
@gamell I haven't taken the time to fully investigate the implications of this update. Pinging people in the atom slack for input/advice.

**Comment by ashleygwilliams** [comment]
glad to see movement on this, we have a marky issue open re: it, https://github.com/npm/marky-markdown/issues/176

**Comment by ashleygwilliams** [comment]
hello! is there any progress on this? anyway i could help? let me know!
