### ISSUE TITLE
Parsing of an hyphen after escaped \\d

### ISSUE THREAD

**Issue by kuzyn** [atom/first-mate#87]
Let me know how I can easily create a test case to reproduce this (i.e. is there a command that let us test an expression with first-mate?)

[My rule](https://github.com/kuzyn/chatscript-tmlanguage/commit/3d1dc83407a55ca5a2a0e5e432d861cf28afc07d) should match `$foo.bar` along with `$foo-bar`

There seem to be an issue parsing the hyphen in this expression (char 14):
`(\\$[a-zA-Z\\d-_]+)(\\.[\\w$-]+)?`

While if it is placed after the underscore, Atom/fm parse it like it should (literal hyphen)
`(\\$[a-zA-Z\\d_-]+)(\\.[\\w$-]+)?`

Other syntax interpreters seems to be fine with the first instance (ST3, regex101)

**Comment by Ingramz** [comment]
From http://www.regular-expressions.info/charclass.html, section "Metacharacters Inside Character Classes"

> The hyphen can be included right after the opening bracket, or right before the closing bracket, or right after the negating caret. Both `[-x]` and `[x-]` match an x or a hyphen. `[^-x]` and `[^x-]` match any character thas is not an x or a hyphen. This works in all flavors discussed in this tutorial. **Hyphens at other positions in character classes where they can't form a range may be interpreted as literals or as errors. Regex flavors are quite inconsistent about this.**

TextMate does not throw an error, but it will skip the hyphen from that character class if you put it between two characters that do not form a range. You may escape the hyphen with a backslash, which will consider that hyphen as a standalone character within the character class or put it in the beginning or end of the character class. Same applies for first-mate.

**Comment by kuzyn** [comment]
This makes perfect sense. Thanks for digging that up @Ingramz !
